name: Send Certificate

on:
  push:
    branches:
      - master
    paths:
      - 'contributions/**/*.txt'

jobs:
  send_certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install Jinja2 requests


      - name: Get previous commit SHA
        id: previous_commit_sha
        run: |
          PREVIOUS_COMMIT_SHA=$(git rev-list --skip=1 -n 1 ${{ github.sha }})
          echo "PREVIOUS_COMMIT_SHA=$PREVIOUS_COMMIT_SHA" >> $GITHUB_ENV

      - name: Find .txt file and extract info
        run: |
          output=$(python find_txt.py ${{ env.PREVIOUS_COMMIT_SHA }})
          IFS=$'\n' read -d '' -r -a arr <<< "$output"
          txt_file=${arr[0]}
          name=${arr[1]}
          email=${arr[2]}
          echo "TXT_FILE=$txt_file" >> $GITHUB_ENV
          echo "NAME=$name" >> $GITHUB_ENV
          echo "EMAIL=$email" >> $GITHUB_ENV

      - name: Get commit hash
        run: |
          short_commit_hash=${{ github.sha }} && short_commit_hash=${short_commit_hash}
          echo "SHORT_COMMIT_HASH=$short_commit_hash" >> $GITHUB_ENV

      - name: Send certificate email
        run: python send_certificate.py "${{ env.NAME }}" "${{ env.EMAIL }}" "${{ env.SHORT_COMMIT_HASH }}"
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
