name: Send Certificate

on:
  push:
    branches:
      - master
    paths:
      - 'contributions/**/*.txt'

jobs:
  send_certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install Jinja2

      - name: Find .txt file
        id: find_txt
        run: |
          txt_file=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep .txt)
          echo "TXT_FILE=$txt_file" >> $GITHUB_ENV

      - name: Extract name and email from .txt file
        id: extract_info
        run: |
          name=$(head -n 1 ${{ env.TXT_FILE }})
          email=$(tail -n 1 ${{ env.TXT_FILE }})
          echo "NAME=$name" >> $GITHUB_ENV
          echo "EMAIL=$email" >> $GITHUB_ENV

      - name: Get commit hash
        run: |
          short_commit_hash=${{ github.sha }} && short_commit_hash=${short_commit_hash::7}
          echo "SHORT_COMMIT_HASH=$short_commit_hash" >> $GITHUB_ENV

      - name: Send certificate email
        run: python send_certificate.py "${{ env.NAME }}" "${{ env.EMAIL }}" "${{ env.SHORT_COMMIT_HASH }}"
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
