name: Send Certificate

on:
  push:
    branches:
      - master
    paths:
      - 'contributions/**/*.txt'

jobs:
  send_certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install Jinja2 requests

      - name: Get file diff between current commit and previous commit
        run: |
          PREVIOUS_COMMIT=$(git rev-list --skip=1 -n 1 ${{ github.sha }})  # Get previous commit hash
          DIFF_OUTPUT=$(git diff --name-only $PREVIOUS_COMMIT ${{ github.sha }})  # Get the file diff
          echo "DIFF_OUTPUT=$DIFF_OUTPUT" >> $GITHUB_ENV

      - name: Find .txt file and extract info
        run: |
          txt_file=$(echo "$DIFF_OUTPUT" | grep 'contributions/.*\.txt$')
          if [[ -z "$txt_file" ]]; then
            echo "No .txt file found in 'contributions' folder or multiple .txt files found."
            exit 1
          fi
          name=$(head -n 1 "$txt_file")
          email=$(sed -n '2p' "$txt_file")
          echo "TXT_FILE=$txt_file" >> $GITHUB_ENV
          echo "NAME=$name" >> $GITHUB_ENV
          echo "EMAIL=$email" >> $GITHUB_ENV

      - name: Get commit hash
        run: |
          short_commit_hash=${{ github.sha }} && short_commit_hash=${short_commit_hash}
          echo "SHORT_COMMIT_HASH=$short_commit_hash" >> $GITHUB_ENV

      - name: Send certificate email
        run: python send_certificate.py "${{ env.NAME }}" "${{ env.EMAIL }}" "${{ env.SHORT_COMMIT_HASH }}"
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
