name: Send Certificate

on:
  push:
    branches:
      - master
    paths:
      - 'contributions/**/*.txt'

jobs:
  send_certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install Jinja2 requests

      - name: Find .txt file and extract info and call the other script
        run: python find_txt.py ${{ github.sha }}
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}